/* Auto-generated by scripts/export_weights.py — do not edit */
#pragma once

/* Load into weights_bo: fread(ptr, 1, LAYER0_TOTAL_BYTES, f) */
#define LAYER0_WEIGHTS_FILE  "layer0_weights.bin"
#define LAYER0_N_OUT_CH      16
#define LAYER0_BUF_BYTES     64
#define LAYER0_TOTAL_BYTES   1024

/* What this file was exported as. The BUILD must agree:
 * a CONV_IN_CH=1 graph fed a CONV_IN_CH=3 weights file reads
 * taps [0:9] as a 3x3 kernel and slices out_shift out of the
 * G plane. Byte 63 of every channel buffer carries the same
 * number so a reader can assert at runtime. */
#define LAYER0_IN_CH         3
#define LAYER0_N_TAPS        27
#define LAYER0_BIAS_SCALE    32.0f

#include "conv_weight_layout.h"
#if LAYER0_IN_CH != CONV_IN_CH
#  error "layer0_weights.bin was exported for a different CONV_IN_CH. Re-run: make weights CONV_IN_CH=<n>"
#endif

/* Per-channel dequantization scale: y_float ≈ out_int16 * scale * (1<<shift) */
static const float layer0_dequant_scales[16] = {
    7.4986263825e-06f,
    8.0352070724e-05f,
    1.3814256236e-05f,
    1.0884304387e-04f,
    2.9798013075e-05f,
    3.6352130866e-05f,
    9.9826163807e-07f,
    1.2979397190e-06f,
    2.9627799993e-05f,
    1.2038508723e-05f,
    1.0038287893e-05f,
    1.0866567822e-03f,
    7.7100540407e-07f,
    5.7334828606e-07f,
    5.3545176715e-07f,
    1.1509162912e-04f,
};

/* Per-channel output right-shift stored at byte 9 of each 64-byte buffer */
static const int layer0_out_shifts[16] = { 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 4 };
