/* Auto-generated by scripts/export_weights.py — do not edit */
#pragma once

/* Load into weights_bo: fread(ptr, 1, LAYER0_TOTAL_BYTES, f) */
#define LAYER0_WEIGHTS_FILE  "layer0_weights.bin"
#define LAYER0_N_OUT_CH      16
#define LAYER0_BUF_BYTES     64
#define LAYER0_TOTAL_BYTES   1024

/* Per-channel dequantization scale: y_float ≈ out_int16 * scale * (1<<shift) */
static const float layer0_dequant_scales[16] = {
    1.4484671646e-06f,
    5.8781805558e-05f,
    5.4939386004e-06f,
    6.9219774417e-05f,
    2.2266383467e-05f,
    2.7051856806e-05f,
    7.2549686413e-07f,
    1.0140085422e-06f,
    2.1876990878e-05f,
    4.5472069123e-06f,
    3.5950400788e-07f,
    8.2117995245e-04f,
    5.8334443946e-07f,
    4.5432246829e-07f,
    3.9414867729e-07f,
    7.9077565350e-05f,
};

/* Per-channel output right-shift stored at byte 9 of each 64-byte buffer */
static const int layer0_out_shifts[16] = { 7, 3, 5, 3, 4, 3, 4, 3, 4, 5, 8, 3, 5, 6, 7, 3 };
