/* Auto-generated by scripts/export_weights.py — do not edit */
#pragma once

/* Load into weights_bo: fread(ptr, 1, LAYER0_TOTAL_BYTES, f) */
#define LAYER0_WEIGHTS_FILE  "layer0_weights.bin"
#define LAYER0_N_OUT_CH      32
#define LAYER0_BUF_BYTES     192
#define LAYER0_TOTAL_BYTES   6144

/* What this file was exported as. The BUILD must agree:
 * a CONV_IN_CH=1 graph fed a CONV_IN_CH=3 weights file reads
 * taps [0:9] as a 3x3 kernel and slices out_shift out of the
 * G plane. Byte 63 of every channel buffer carries the same
 * number so a reader can assert at runtime. */
#define LAYER0_IN_CH         3
#define LAYER0_KSIZE         7
#define LAYER0_N_TAPS        147
#define LAYER0_BIAS_SCALE    32.0f
/* out_shift sized against the 'l1' accumulator bound */

#include "conv_weight_layout.h"
#if LAYER0_IN_CH != CONV_IN_CH
#  error "layer0_weights.bin was exported for a different CONV_IN_CH. Re-run: make weights CONV_IN_CH=<n>"
#endif
#if LAYER0_KSIZE != CONV_KSIZE
#  error "layer0_weights.bin was exported for a different CONV_KSIZE. Re-run: make weights CONV_KSIZE=<k>"
#endif

/* Per-channel dequantization scale: y_float ≈ out_int16 * scale * (1<<shift) */
static const float layer0_dequant_scales[32] = {
    9.9922111713e-06f,
    7.8380155218e-06f,
    9.1587882482e-06f,
    5.3286934703e-06f,
    5.9275573311e-06f,
    6.2199431212e-06f,
    7.0525309528e-06f,
    8.9409478705e-06f,
    6.0332618069e-06f,
    5.7577690996e-06f,
    5.3543309536e-06f,
    6.0299818091e-06f,
    5.1494883528e-06f,
    4.3750229873e-06f,
    4.8479906719e-06f,
    6.9095591299e-06f,
    3.9355193510e-06f,
    4.3293021841e-06f,
    3.7620427554e-06f,
    5.2440002634e-06f,
    4.6808468700e-06f,
    4.2003582965e-06f,
    3.6586988320e-06f,
    4.0323436128e-06f,
    4.7382006037e-06f,
    3.8061230667e-06f,
    4.5540846074e-06f,
    4.3472789115e-06f,
    4.9733569887e-06f,
    3.5949515820e-06f,
    4.1322532662e-06f,
    3.8129088131e-06f,
};

/* Per-channel output right-shift stored at byte 9 of each 64-byte buffer */
static const int layer0_out_shifts[32] = { 3, 3, 3, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 5, 4, 4, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5 };
