#include "vot_source.h"

#include <cerrno>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace vot {
namespace {

// ---------------------------------------------------------------------------
// A small strict JSON reader
// ---------------------------------------------------------------------------
// Hand-rolled rather than vendored because the board rootfs carries no JSON
// library and the input is machine-generated by one script in this repo. STRICT
// is the load-bearing word: every failure below returns an error with an offset,
// because the alternative — a lenient parser that silently yields a default —
// is how a manifest field ends up read as 0 and a whole run comes back plausible
// and wrong. It does not attempt \u escapes; the manifest has none, and a parser
// that pretends to handle something it does not is worse than one that says no.

struct Value {
    enum Type { Null, Bool, Num, Str, Arr, Obj } type = Null;
    bool        b = false;
    double      num = 0.0;
    std::string str;
    std::vector<Value> arr;
    std::vector<std::pair<std::string, Value>> obj;

    const Value *find(const char *key) const {
        if (type != Obj) return nullptr;
        for (const auto &kv : obj)
            if (kv.first == key) return &kv.second;
        return nullptr;
    }
};

struct Parser {
    const char *p, *end;
    std::string err;

    bool fail(const char *what) {
        char buf[128];
        snprintf(buf, sizeof buf, "%s at byte %ld", what, (long)(p - base));
        err = buf;
        return false;
    }
    const char *base;

    void ws() {
        while (p < end && (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r')) ++p;
    }
    bool lit(const char *s) {
        size_t n = strlen(s);
        if ((size_t)(end - p) < n || memcmp(p, s, n) != 0) return false;
        p += n;
        return true;
    }
    bool value(Value &v);

    bool string(std::string &out) {
        if (p >= end || *p != '"') return fail("expected string");
        ++p;
        out.clear();
        while (p < end && *p != '"') {
            if (*p == '\\') {
                if (++p >= end) return fail("truncated escape");
                switch (*p) {
                    case '"':  out += '"';  break;
                    case '\\': out += '\\'; break;
                    case '/':  out += '/';  break;
                    case 'b':  out += '\b'; break;
                    case 'f':  out += '\f'; break;
                    case 'n':  out += '\n'; break;
                    case 'r':  out += '\r'; break;
                    case 't':  out += '\t'; break;
                    default:   return fail("unsupported escape");
                }
                ++p;
            } else {
                out += *p++;
            }
        }
        if (p >= end) return fail("unterminated string");
        ++p;
        return true;
    }
};

bool Parser::value(Value &v) {
    ws();
    if (p >= end) return fail("unexpected end of input");
    switch (*p) {
        case 'n': v.type = Value::Null; return lit("null") ? true : fail("expected null");
        case 't': v.type = Value::Bool; v.b = true;
                  return lit("true") ? true : fail("expected true");
        case 'f': v.type = Value::Bool; v.b = false;
                  return lit("false") ? true : fail("expected false");
        case '"': v.type = Value::Str;  return string(v.str);
        case '[': {
            v.type = Value::Arr;
            ++p; ws();
            if (p < end && *p == ']') { ++p; return true; }
            for (;;) {
                v.arr.emplace_back();
                if (!value(v.arr.back())) return false;
                ws();
                if (p < end && *p == ',') { ++p; continue; }
                if (p < end && *p == ']') { ++p; return true; }
                return fail("expected ',' or ']'");
            }
        }
        case '{': {
            v.type = Value::Obj;
            ++p; ws();
            if (p < end && *p == '}') { ++p; return true; }
            for (;;) {
                ws();
                std::string key;
                if (!string(key)) return false;
                ws();
                if (p >= end || *p != ':') return fail("expected ':'");
                ++p;
                v.obj.emplace_back(key, Value{});
                if (!value(v.obj.back().second)) return false;
                ws();
                if (p < end && *p == ',') { ++p; continue; }
                if (p < end && *p == '}') { ++p; return true; }
                return fail("expected ',' or '}'");
            }
        }
        default: {
            char *tail = nullptr;
            // The manifest is NUL-terminated by manifest_load/manifest_parse's
            // caller contract (both take a length and copy into a std::string),
            // so strtod cannot run off the end.
            double d = strtod(p, &tail);
            if (tail == p) return fail("expected a value");
            v.type = Value::Num;
            v.num  = d;
            p = tail;
            return true;
        }
    }
}

// ---------------------------------------------------------------------------
// typed field access — every one of these can FAIL, and says which key
// ---------------------------------------------------------------------------
bool need(const Value &o, const char *key, Value::Type t,
          const Value **out, std::string &err) {
    const Value *v = o.find(key);
    if (!v) { err = std::string("manifest is missing '") + key + "'"; return false; }
    if (v->type != t) { err = std::string("manifest key '") + key + "' has the wrong type"; return false; }
    *out = v;
    return true;
}

bool num_field(const Value &o, const char *key, double &dst, std::string &err) {
    const Value *v = nullptr;
    if (!need(o, key, Value::Num, &v, err)) return false;
    dst = v->num;
    return true;
}

bool int_field(const Value &o, const char *key, int &dst, std::string &err) {
    double d = 0.0;
    if (!num_field(o, key, d, err)) return false;
    if (d != std::floor(d)) { err = std::string("manifest key '") + key + "' is not an integer"; return false; }
    dst = (int)d;
    return true;
}

bool str_field(const Value &o, const char *key, std::string &dst, std::string &err) {
    const Value *v = nullptr;
    if (!need(o, key, Value::Str, &v, err)) return false;
    dst = v->str;
    return true;
}

// (row, col, h, w), the manifest's own order — vot_prepare.reduce_box emits
// centre-convention boxes, so this is a copy and not a conversion. If that ever
// changes it changes HERE and in reduce_box together, which is why the manifest
// spells the convention out in `gt_convention`.
bool box_from(const Value &v, Box &b, const char *what, std::string &err) {
    if (v.type != Value::Arr || v.arr.size() != 4) {
        err = std::string(what) + ": expected 4 numbers"; return false;
    }
    for (const Value &e : v.arr)
        if (e.type != Value::Num) { err = std::string(what) + ": non-numeric"; return false; }
    b.row = v.arr[0].num; b.col = v.arr[1].num;
    b.h   = v.arr[2].num; b.w   = v.arr[3].num;
    return true;
}

}  // namespace

// ---------------------------------------------------------------------------
bool manifest_parse(const char *text, size_t len, Manifest &m, std::string &err)
{
    std::string owned(text, len);          // guarantees the NUL strtod relies on
    Parser ps;
    ps.base = owned.c_str();
    ps.p    = owned.c_str();
    ps.end  = owned.c_str() + owned.size();

    Value root;
    if (!ps.value(root)) { err = ps.err; return false; }
    if (root.type != Value::Obj) { err = "manifest root is not an object"; return false; }

    m = Manifest{};
    if (!int_field(root, "schema",      m.schema,      err)) return false;
    if (!str_field(root, "sequence",    m.sequence,    err)) return false;
    if (!int_field(root, "frames",      m.frames,      err)) return false;
    if (!int_field(root, "rows",        m.rows,        err)) return false;
    if (!int_field(root, "cols",        m.cols,        err)) return false;
    if (!int_field(root, "channels",    m.channels,    err)) return false;
    if (!str_field(root, "blob",        m.blob,        err)) return false;
    if (!str_field(root, "blob_md5",    m.blob_md5,    err)) return false;
    if (!str_field(root, "gt_format",   m.gt_format,   err)) return false;
    if (!str_field(root, "anchors_source", m.anchors_source, err)) return false;
    if (!int_field(root, "empty_boxes", m.empty_boxes, err)) return false;
    if (!int_field(root, "roi_exceeds_frame", m.roi_exceeds_frame, err)) return false;
    if (!num_field(root, "min_box_side", m.min_box_side, err)) return false;

    // frame_bytes is CARRIED, not derived, and then cross-checked below. The
    // manifest is the authority on its own layout; recomputing it here would be a
    // second implementation of the rule, which is the shape of bug Phase 1 found
    // in reduce_box (two copies of one wrong rule agreeing with each other).
    {
        double fb = 0.0;
        if (!num_field(root, "frame_bytes", fb, err)) return false;
        if (fb <= 0.0 || fb != std::floor(fb)) { err = "frame_bytes is not a positive integer"; return false; }
        m.frame_bytes = (size_t)fb;
    }

    const Value *lb = root.find("luma_blob");
    if (lb && lb->type == Value::Str) m.luma_blob = lb->str;   // null at channels=1

    if (m.schema != 1) {
        char buf[96];
        snprintf(buf, sizeof buf, "manifest schema %d, this build understands 1", m.schema);
        err = buf;
        return false;
    }
    if (m.rows <= 0 || m.cols <= 0 || m.frames <= 0) { err = "degenerate geometry"; return false; }
    if (m.channels != 1 && m.channels != 3) { err = "channels must be 1 or 3"; return false; }
    if (m.frame_bytes != (size_t)m.rows * m.cols * m.channels) {
        err = "frame_bytes disagrees with rows*cols*channels";
        return false;
    }

    const Value *gt = nullptr;
    if (!need(root, "groundtruth", Value::Arr, &gt, err)) return false;
    if ((int)gt->arr.size() != m.frames) { err = "groundtruth length != frames"; return false; }
    m.groundtruth.resize(gt->arr.size());
    for (size_t i = 0; i < gt->arr.size(); ++i)
        if (!box_from(gt->arr[i], m.groundtruth[i], "groundtruth", err)) return false;

    const Value *jobs = nullptr;
    if (!need(root, "jobs", Value::Arr, &jobs, err)) return false;
    m.jobs.reserve(jobs->arr.size());
    for (const Value &jv : jobs->arr) {
        if (jv.type != Value::Obj) { err = "job is not an object"; return false; }
        Job j;
        if (!int_field(jv, "anchor", j.anchor, err)) return false;
        if (!int_field(jv, "length", j.length, err)) return false;
        std::string dir;
        if (!str_field(jv, "direction", dir, err)) return false;
        if (dir == "forward")       j.forward = true;
        else if (dir == "backward") j.forward = false;
        else { err = "job direction is neither forward nor backward"; return false; }
        const Value *ib = jv.find("init_box");
        if (!ib || !box_from(*ib, j.init_box, "init_box", err)) {
            if (err.empty()) err = "job is missing init_box";
            return false;
        }
        if (j.anchor < 0 || j.anchor >= m.frames) { err = "job anchor out of range"; return false; }
        // Derivable, and CHECKED rather than derived — a length that disagrees
        // with the anchor means the manifest and the direction convention have
        // drifted apart, and that is exactly the failure that reads as "a tracker
        // that runs backwards" rather than as an error.
        const int expect = j.forward ? (m.frames - j.anchor) : (j.anchor + 1);
        if (j.length != expect) { err = "job length disagrees with anchor and direction"; return false; }
        m.jobs.push_back(j);
    }
    if (m.jobs.empty()) { err = "manifest has no jobs"; return false; }
    return true;
}

bool manifest_load(const std::string &path, Manifest &m, std::string &err)
{
    FILE *f = fopen(path.c_str(), "rb");
    if (!f) { err = "cannot open " + path + ": " + strerror(errno); return false; }
    std::string text;
    char buf[65536];
    size_t n;
    while ((n = fread(buf, 1, sizeof buf, f)) > 0) text.append(buf, n);
    const bool bad = ferror(f) != 0;
    fclose(f);
    if (bad) { err = "read error on " + path; return false; }
    if (text.empty()) { err = path + " is empty"; return false; }
    return manifest_parse(text.data(), text.size(), m, err);
}

// ---------------------------------------------------------------------------
bool Blob::load(const std::string &path, const Manifest &m, std::string &err)
{
    const auto t0 = std::chrono::steady_clock::now();
    data_.clear();
    frame_bytes_ = 0;
    frames_ = 0;
    secs_ = 0.0;

    const size_t want = m.frame_bytes * (size_t)m.frames;
    FILE *f = fopen(path.c_str(), "rb");
    if (!f) { err = "cannot open " + path + ": " + strerror(errno); return false; }

    // ONE sequential read into heap, sized from the manifest. The buffer is
    // allocated at exactly `want` and read in large chunks: peak heap is one
    // sequence (1269 MB for flamingo1, the largest in stb2022), against 12 GB.
    data_.resize(want);
    size_t got = 0;
    while (got < want) {
        const size_t n = fread(data_.data() + got, 1, want - got, f);
        if (n == 0) break;
        got += n;
    }
    // A byte PAST the expected end is as wrong as a byte short: it means the blob
    // and the manifest disagree about geometry or frame count, and every frame
    // offset after the first is then a guess.
    char extra;
    const bool longer = (fread(&extra, 1, 1, f) == 1);
    const bool bad = ferror(f) != 0;
    fclose(f);

    if (bad)    { data_.clear(); err = "read error on " + path; return false; }
    if (got != want || longer) {
        char b[192];
        snprintf(b, sizeof b, "%s: %zu bytes, manifest says %d frames x %zu = %zu",
                 path.c_str(), longer ? got + 1 : got, m.frames, m.frame_bytes, want);
        data_.clear();
        err = b;
        return false;
    }

    frame_bytes_ = m.frame_bytes;
    frames_      = m.frames;
    secs_ = std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count();
    return true;
}

const uint8_t *Blob::frame(int i) const
{
    if (i < 0 || i >= frames_) return nullptr;
    return data_.data() + (size_t)i * frame_bytes_;
}

// ---------------------------------------------------------------------------
std::vector<int> job_order(const Job &j, int frames)
{
    std::vector<int> order;
    if (j.anchor < 0 || j.anchor >= frames) return order;
    if (j.forward) {
        order.reserve((size_t)(frames - j.anchor));
        for (int i = j.anchor; i < frames; ++i) order.push_back(i);
    } else {
        order.reserve((size_t)(j.anchor + 1));
        for (int i = j.anchor; i >= 0; --i) order.push_back(i);
    }
    return order;
}

// ---------------------------------------------------------------------------
void Trajectory::begin(const Job &j)
{
    boxes_.clear();
    ms_.clear();
    kinds_.clear();
    anchor_ = j.anchor;
    length_ = j.length;
    boxes_.reserve((size_t)j.length);
    ms_.reserve((size_t)j.length);
    kinds_.reserve((size_t)j.length);
}

void Trajectory::push_init(double ms)
{
    boxes_.push_back(Box{});
    ms_.push_back(ms);
    kinds_.push_back('i');
}

void Trajectory::push(const Box &b, double ms)
{
    boxes_.push_back(b);
    ms_.push_back(ms);
    kinds_.push_back('r');
}

std::string Trajectory::as_text() const
{
    std::string out;
    char line[128];
    for (size_t i = 0; i < kinds_.size(); ++i) {
        if (kinds_[i] == 'i') {
            snprintf(line, sizeof line, "%d\n", SPECIAL_INITIALIZATION);
        } else {
            // CENTRE -> the toolkit's top-left x,y,w,h. The only place in this
            // file where the two conventions meet.
            const Box &b = boxes_[i];
            snprintf(line, sizeof line, "%.4f,%.4f,%.4f,%.4f\n",
                     b.col - b.w / 2.0, b.row - b.h / 2.0, b.w, b.h);
        }
        out += line;
    }
    return out;
}

bool Trajectory::write(const std::string &dir, const std::string &sequence,
                       std::string &err) const
{
    if (kinds_.empty())            { err = "trajectory is empty"; return false; }
    if (kinds_[0] != 'i')          { err = "trajectory index 0 is not the init special"; return false; }
    // Short by one is the single most likely bookkeeping slip here and it scores
    // as a tracker that stopped early rather than as an error, so it is checked
    // at the only moment the expected count is still known.
    if ((int)kinds_.size() != length_) {
        char b[128];
        snprintf(b, sizeof b, "trajectory has %zu entries, job length is %d",
                 kinds_.size(), length_);
        err = b;
        return false;
    }

    char stem[512];
    snprintf(stem, sizeof stem, "%s/%s_%08d", dir.c_str(), sequence.c_str(), anchor_);

    std::string traj = std::string(stem) + ".txt";
    FILE *f = fopen(traj.c_str(), "w");
    if (!f) { err = "cannot write " + traj + ": " + strerror(errno); return false; }
    const std::string text = as_text();
    fwrite(text.data(), 1, text.size(), f);
    const bool traj_bad = (ferror(f) != 0);
    if (fclose(f) != 0 || traj_bad) { err = "write error on " + traj; return false; }

    std::string tv = std::string(stem) + "_time.value";
    f = fopen(tv.c_str(), "w");
    if (!f) { err = "cannot write " + tv + ": " + strerror(errno); return false; }
    // One float per line, one per region — the toolkit reads these with an
    // unconditional float(), so a blank line raises rather than meaning
    // "no timing" (phase0b.md).
    for (double ms : ms_) fprintf(f, "%.3f\n", ms);
    const bool tv_bad = (ferror(f) != 0);
    if (fclose(f) != 0 || tv_bad) { err = "write error on " + tv; return false; }

    return true;
}

}  // namespace vot
